### ISSUE TITLE
Error when running for first time if database hasn't been populated.

### ISSUE THREAD

**Issue by RSWilson1** [eastgenomics/Ploutos#11] opened 2022-08-03 15:40 UTC
Error details:

Error from Forms when no data in the database, noticed from DateForm.

How to replicate:
Fresh install, run python manage.py runserver
Error output
AttributeError: 'NoneType' object has no attribute 'date'

This can be solved by populating the db, with `python runscript -v2 populate_db`

**Comment by jethror1** [comment] 2022-08-04 10:31
can just add this a constraint also to the readme to say the script must be run first.

@rklocke will it cause issues with calculations if it was run during the day and then at midnight, or would the first days calculations just be slightly smaller?

**Comment by rklocke** [comment] 2022-08-04 11:13
@jethror1 should be easy to solve, it's just because it gets the earliest date in the DailyOrgRunningTotals table to set the earliest possible date that can be selected on the form datepicker. Could check if first_date is empty (no entries in db), and if so then set the 'min' on the datepicker to today.

if it was run in the day then just after midnight, it should just mean the first day's calculations are smaller. If it was run twice in a single day I think it would just overwrite the running total values (as there is a unique date constraint) but would cause issues for other tables as too many rows would be added.

can add fix above when everything is merged?

**Comment by JasonLing95** [comment] 2022-11-28 13:38
The issue is solved by not having db connection in forms.py when running migration but only initiate db connection when form class is called.

**Closed by JasonLing95** 2022-11-28 13:38 UTC
Labels: bug
